TEST
IlerioDef/menu_restaurant pull request #1
Opened 2023-08-22 04:10 UTC by IlerioDef

TEST

2023-08-25 13:52 UTC, Klavionik requested changes

2023-08-25 13:52 UTC, Klavionik commented on .gitignore
> +!/.TEMP/
Зачем ты игноришь package-lock.json, package.json, taiwind.config.js, а затем разигнориваешь обратно? Их в принципе не нужно игнорить, они коммитятся в проект. Т.е. эти 6 правил нужно удалить совсем.

Еще перед названиями папок и файлов не обязательно писать `/`.

2023-08-25 13:52 UTC, Klavionik commented on Dockerfile
> +# syntax=docker/dockerfile:1
Ну это не самая полезная штука, можно и не писать. %)

2023-08-25 13:52 UTC, Klavionik commented on Dockerfile
> +FROM python:3.9.0-alpine
alpine-образы хороши своим размером, но это не всегда хороший выбор для сборки Python-проектов, особенно тех, которым нужны библиотеки с C-зависимостями (например, psycopg). 

Вот тут поподробнее: https://pythonspeed.com/articles/alpine-docker-python/

Скажу так - я тоже стремился использовать alpine, чтобы типа собиралось быстрее и образы были меньше. Но в итоге это добавляло столько геморроя, что я отказался от них в пользу slim вариантов. alpine беру только там, где от него не будет лишних проблем.

2023-08-25 13:52 UTC, Klavionik commented on Dockerfile
> +COPY . /code/
После того, как ты использовал `WORKDIR`, это новая рабочая директория образа. Можно писать просто `.` вместо `/code`.

2023-08-25 13:52 UTC, Klavionik commented on compose.yaml
> +        command: python manage.py runserver 0.0.0.0:8000
Тут ситуация из разряда "вы либо крестик снимите, либо трусы наденьте." =) Смотри, у тебя уже есть команда для запуска по-умолчанию в `Dockerfile`. Тут ты ее оверрайдишь на другую почти такую же. Смысла в этом немного, только лишняя дупликация кода (а это почти всегда плохой признак).

Лучше выбрать один из следующих вариантов:

1. Убрать CMD из Dockerfile, оставить command.
2. Убрать command, дописать в CMD адрес и порт.
3. Перенести буквы из CMD в ENTRYPOINT, а в comamnd оставить только адрес и порт.

2023-08-25 13:52 UTC, Klavionik commented on compose.yaml
> +        container_name: docker_django
Лучше давать контейнерам более уникальные имена, потому что имена существуют в общем неймспейсе. Если ты заведешь еще какой-нибудь проект, и там назовешь контейнер так же, возникнут проблемы.

В целом интересно узнать, как ты используешь container_name. Достаточно бесполезная штука, как по мне, но возможно я не нашел ей применения.

2023-08-25 13:52 UTC, Klavionik commented on uploads/uploads/super-sheikh-meal-two.jpg
Странная структура директорий. У тебя одна папка uploads вложена в другую папку uploads, и в них лежит файл с одинаковым названием. Уверен, что так и должно быть?

2023-08-25 13:52 UTC, Klavionik commented on src/styles.css
> +@tailwind base;
Папка с названием `src` имеет определенное значение. src значит `sources`, и во многих языках исходный код проекта принято складывать именно в эту папку. В Python есть похожая конвенция, называется `src layout` (https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/). Но это не про твой случай.

Я почти уверен, что файлу со стилями из тейлвинда можно найти более понятное место, тем более, как мне кажется, этот файл нужен только для разработки.

2023-08-25 13:52 UTC, Klavionik commented on order/context_processors.py
> +    return {'menu_order': Order(request)}
Процессоры контекста полезны, когда тебе нужно дать всем шаблонам доступ к какой-то глобальной информации. Обрати внимание, какие процессоры включены по умолчанию и в чем их смысл. 

В случае с информацией о заказе это смысла не имеет. Но здорово, что ты в принципе узнал про процессоры контекста и применил их на практике.

2023-08-25 13:52 UTC, Klavionik commented on core/models.py
> +    name = models.CharField(max_length=30, null=True)
1) Делать текстовые поля нуллабл не рекомендуется (https://docs.djangoproject.com/en/4.2/ref/models/fields/#null)
2) Не совсем понятно, зачем в принципе может быть нужен аллерген без названия. Это ж вообще единственное поле у этой модели. :)

2023-08-25 13:52 UTC, Klavionik commented on core/models.py
> +    name = models.CharField(max_length=255, null=False, blank=False)
null=False, blank=False это дефолт у всех полей, нет смысла писать это. Зато, мне кажется, есть смысл сделать названия блюд уникальными.

2023-08-25 13:52 UTC, Klavionik commented on core/models.py
> +    price = models.IntegerField()
Для ценыпо смыслу больше подошло бы `FloatField`. В реальности же вообще используют `DecimalField`, у которого не будет проблемы с расчетом цен и скидок (https://docs.python.org/3/faq/design.html#why-are-floating-point-calculations-so-inaccurate). И не нужно будет хранить цены умноженную на 100, чтобы потом делить ее на 100 в нескольких местах, размазывая логику.

2023-08-25 13:52 UTC, Klavionik commented on core/models.py
> +    food_energy = models.IntegerField()
"Энергия еды" так себе нейминг, как по мне - можно догадаться, о чем это, конечно, но понятнее было бы с названием типа "calories".

2023-08-25 13:52 UTC, Klavionik commented on core/models.py
> +    description = models.CharField(max_length=255, null=False, blank=True, default='Tasty meal')
Описание блюда - это как будто бы то, что должно быть у каждого блюда, и должно быть разное. Поэтому blank=True и default тут как будто не подходят.

2023-08-25 13:52 UTC, Klavionik commented on core/models.py
> +        return str(self.name)
name это уже str, мне кажется тут не нужно еще одно приведение.

2023-08-25 13:52 UTC, Klavionik commented on core/models.py
> +class Item(models.Model):
`Item` - слишком абстрактное название. Лучше было бы `MenuItem`. Или чтобы эта модель была в приложении `menu`, а не `core` - тогда неймспейсинг создавал бы нужный для правильного понимания контекст.

2023-08-25 13:52 UTC, Klavionik commented on core/models.py
> +                return "https://https://placehold.co/240x240"
Логику создания миниатюры при загрузке картинки лучше реализовать с помощью сигналов. Тогда этот метод станет не нужен, можно будет делать просто `item.thumbnail.url`.

Кроме того, если ты используешь `return` внутри `if`, `else` тебе уже не нужен.

Еще обрати внимание на URL заглушки, в нем опечатка.

2023-08-25 13:52 UTC, Klavionik commented on core/models.py
> +    def make_thumbnail(self, image, size=(240, 240)):
Логика этой функции особо не имеет отношения к блюду - ее можно унести в другое место отсюда.

2023-08-25 13:52 UTC, Klavionik commented on core/models.py
> +    allergen = models.ManyToManyField(Allergen, blank=True)
Для m2m поля больше подходит название в мн. ч.

2023-08-25 13:52 UTC, Klavionik commented on core/models.py
> +        else: return None
Кривенький метод. :c

Во-первхы условие не будет работать правильно. Ты ждешь, что оно будет False при отсутствии аллергенов, да? А оно не будет False никогда. Почему - предлагаю тебе разобраться самому.

Во-вторых, проблемы с кодстайлом. Много лишних пустых строк, избыточный `else`, нет переноса строки после `else`.

В-третьих, смысл существования метода в принципе отсутствует. Тоже самое ты можешь узнать по полю `allergen` - `item.allergen.all()`. Тебе нужно лучше узнать, как работать с m2m-связями в моделях.

2023-08-25 13:52 UTC, Klavionik commented on core/models.py
> +        return self.price / 100
Антипаттерн magic numbers. https://stackoverflow.com/questions/47882/what-is-a-magic-number-and-why-is-it-bad

2023-08-25 13:52 UTC, Klavionik commented on core/views.py
> +# Create your views here.
Забыл удалить комментарий.

2023-08-25 13:52 UTC, Klavionik commented on core/views.py
> +    menu = Item.objects.all()
Переменная `menu`  переписывает название фунции `menu`. Конкретно тут это не мешает, но вообще лучше так не делать. В конце концов, результат выполнения вызова `Item.objects.all` это `items`, а не меню.

2023-08-25 13:52 UTC, Klavionik commented on core/views.py
> +        'allergens': allergens,
Аллергены никак не используются в шаблоне меню, их можно смело убрать отсюда.

2023-08-25 13:52 UTC, Klavionik commented on core/views.py
> +        'allergens': allergens,
Еще советую начинать пользоваться generic views. Вот для таких случаев как раз существует ListView: https://docs.djangoproject.com/en/4.2/ref/class-based-views/generic-display/#listview

2023-08-25 13:52 UTC, Klavionik commented on menu_restaurant/settings.py
>  DEBUG = True
Комментарий оставляю на одну строчку, но это относится к настройкам вообще: не надо хардкодить настройки, лучше брать их из внешней конфигурации (см. 12-factor app).

2023-08-25 13:52 UTC, Klavionik commented on menu_restaurant/settings.py
>  DEBUG = True
Еще я не смог понять, как у тебя работает отображение загруженных файлов (картинок блюд). Где MEDIA_ROOT, где MEDIA_URL? Где ты используешь `get_thumbnail`?

2023-08-25 13:52 UTC, Klavionik commented on menu_restaurant/settings.py
> +    'core',
Порядок указания установленных аппов обычно повторяет правила импорта модулей: сначала встроенные в Django, потом third-party, потом аппы проекта.

2023-08-25 13:52 UTC, Klavionik commented on menu_restaurant/settings.py
> +# Default primary request field type
Зачем ты поменял key на request? Oo

2023-08-25 13:52 UTC, Klavionik commented on menu_restaurant/settings.py
> +#Add this in your settings.py file:
Зачем тут этот комментарий?

2023-08-25 13:52 UTC, Klavionik commented on order/views.py
> +def order(request, item_id=None, action="increase"):
А зачем тут дефолтный аргумент у item_id? Как использовать это view без item_id - как ты узнаешь, какое блюдо добавить или убрать?

2023-08-25 13:52 UTC, Klavionik commented on order/views.py
> +        menu_order.save()
Troubled code. x_X 

Что будет, если `item_id is None == True`? 
Что будет, если `item_id is not None == True`, но в переменной action - "foobar"? 
Почему, если прислать action "decrease", блюдо все равно добавляется в заказ? 
Если ты добавляешь только по 1-му блюду за раз, зачем нужен параметр quantity?

2023-08-25 13:52 UTC, Klavionik commented on order/views.py
> +        return redirect(request.GET.get('next'))
Тут можно использовать walrus operator, чтобы не писать одно и то же дважды.

2023-08-25 13:52 UTC, Klavionik commented on order/views.py
> +
Лишняя пустая строчка.

2023-08-25 13:52 UTC, Klavionik commented on order/order.py
> +class Order(object):
Зачем здесь наследование от `object`?

2023-08-25 13:52 UTC, Klavionik commented on order/order.py
> +            menu_order = self.session[settings.ORDER_SESSION_ID] = {}
Чтобы не писать такой код, есть полезный метод `setdefault`.

2023-08-25 13:52 UTC, Klavionik commented on order/order.py
> +    #     yield item
Забыл удалить закомментированный код.

2023-08-25 13:52 UTC, Klavionik commented on order/order.py
> +        self.menu_order[request] = value
Вот это что-то странное. Как ты это используешь?

2023-08-25 13:52 UTC, Klavionik commented on order/order.py
> +            self.menu_order[product_id] = temp + quantity
Этот код можно значительно улучшить, применив правильный метод словаря. Ты с этим методом знаком.

2023-08-25 13:52 UTC, Klavionik commented on order/order.py
> +        self.save()
Ты вызываешь `save` снаружи (в `order.views.order`) и вызываешь его тут. Один из этих вызовов явно лишний.

2023-08-25 13:52 UTC, Klavionik commented on order/views.py
> +        menu_order.save()
А, я понял! В ветке `decrease` ты добавляешь блюдо с quantity `-1` (на ноуте в светлом помещении плохо видно минус...). 

Ты смешиваешь в одном методе два противоположных фунционала, не надо так делать. "Добавлять минус один продукт", ну это же интуитивно что-то странное. :)

2023-08-25 13:52 UTC, Klavionik commented on order/order.py
> +            total_price += item.price * self.menu_order[key]
Тут можно улучшить читаемость, переименовав `key` в `product_id`, и уменьшить нагрузку на БД - что если у твоего пользователя в корзине 20 товаров? Второе оставлю тебе на подумать (это же касается остальных методов, где есть запросы в БД в цикле).

2023-08-25 13:52 UTC, Klavionik commented on order/order.py
> +        return quantity
Для этого в Python есть целая встроенная фунция. :)

2023-08-25 13:52 UTC, Klavionik commented on readme.md
> +<!-- PROJECT SHIELDS -->
Название этого файла принято писать капсом. Гитхаб понимает и так, он умный. Но тем не менее. %)

2023-08-25 13:52 UTC, Klavionik commented on readme.md
> +    docker-compose up -d --build
Ну флаг `--build` тут не нужен, если образов нет, соберет и без него.

2023-08-25 13:52 UTC, Klavionik commented on readme.md
> +    docker exec -it docker_django sh
А, так вот зачем тебе `container_name` (это я в другом комментарии удивлялся).

Есть же вариант проще: `docker compose exec web ./manage.py migrate`.

Еще я тебе раньше рассказывать, как делать миграции автоматически (с помощью энтрипоинта или one-off job). К последнему даже давал пример.

2023-08-25 13:52 UTC, Klavionik commented on core/models.py
> +    slug = models.SlugField()
Было бы здорово, если бы slug генерировался автоматически на основе названия блюда, например.

2023-08-25 13:52 UTC, Klavionik commented on core/views.py
> +    return render(request, "core/core.html")
Не нашел, где используется это вью. У него вроде никакого URL нету. 🤔

2023-08-25 14:02 UTC, Klavionik commented on Dockerfile
> +RUN pip install --upgrade pip
Самое важное замечание по этому Dockerfile - плохая работа с кэшированием слоев. Ты копируешь сначала requirements.txt, т.е. ты как будто где-то это увидел, но не понял, зачем так делают. А это важно.

https://docs.docker.com/build/guide/layers/

2023-08-25 14:15 UTC, Klavionik commented
Оставил комментарии, браток.

Я не успел посмотреть шаблоны и все такое, дизайн не оценивал (по понятным причинам). Но было бы здорово, если бы ты поменял иконки на более подходящие для добавления товара и для корзины. Сейчас выглядит так, будто мне предлагают что-то скачать или скопировать. %)

В общем и целом, я бы оценил на 5 из 10, где 10. 

Ты хорошо следишь за кодстайлом (кроме шаблонов - там чот полный пэ творится): либо ты аккуратно пишешь код, либо не забываешь его форматировать тулзами. Следующий шаг - научиться интегрировать в проект внешний форматтер типа black в пре-коммит хуки.

Здорово, что ты пытаешься делить проект на приложения по функционалу (хотя необходимость такого разделения конкретно в этом проекте стремится к нулю, в целом это хороший ход).

Кажется, ты хорошо справляешься с Docker, у меня нашлось только одно важное замечание.

Однако есть и печальные моменты  Ты часто забываешь использовать полезные встроенные методы и пишешь свою собствееную логику там, где можно этого избежать. Есть проблемы с пониманием того, как работают условия, и в целом с дизайном класса Order (вызывать add с минусовым quantity - это прям ну беда). Кажется, ты не очень хорошо понимаешь, как работают связи в Django, и не знаешь про generic views. Это все достаточно базовые штуки, и честно, я ожидал что на этом отрезке твоего путешествия подобных проблем уже не будет. Возможно, тебе нужно больше приналечь на обычный, "безджанговый" питон. Убрать пробелы в базе, так сказать.

В общем и целом, ты весьма неплохо справился! Я прошелся по readme, запустил проектик и он заработал: на моей памяти не все люди (с реальным рабочим опытом) справлялись с этим без оговорок. 🌚

2023-08-25 22:10 UTC, merged

2023-10-01 22:28 UTC, IlerioDef commented on .gitignore
> +!/.TEMP/
Done

2023-10-02 00:35 UTC, IlerioDef commented on Dockerfile
> +# syntax=docker/dockerfile:1
Done

2023-10-02 00:37 UTC, IlerioDef commented on Dockerfile
> +FROM python:3.9.0-alpine
redone to slim version

2023-10-02 00:51 UTC, IlerioDef commented on Dockerfile
> +RUN pip install --upgrade pip
Перенес кэшируемые слои (постгрес, обновление ПИПа) выше по стэку, теперь некэшируемым остается только слои копирования и установки из requirements)

2023-10-02 00:55 UTC, IlerioDef commented on compose.yaml
> +        command: python manage.py runserver 0.0.0.0:8000
выбрал вариант. Причина: если предположим усложнение системы в дальнейшем, то все взаимоотношения между контейнерами правильней и удобней редактировать в компоузе

2023-10-02 00:57 UTC, IlerioDef commented on compose.yaml
> +        container_name: docker_django
Переименовал в menu_restaurant. 
Мне кажется так глазу приятней, когда есть имя, а не только код

2023-10-09 23:36 UTC, IlerioDef commented on src/styles.css
> +@tailwind base;
Я знаю, почему папка src называется src 🌚. Считаю твои замечания к исходнику тейлвинда и его расположению, скажем так, необоснованными именно в ключе описанного по ссылке. Но переменстил в корень проекта и переименовал в tailwind_src.css

2023-10-09 23:42 UTC, IlerioDef commented on core/models.py
> +    name = models.CharField(max_length=30, null=True)
Переделал на blank=True (т.е. если нет - то аллергенов нет). Так или иначе, - blank=True, unique=True, null=True, согласно описанию по ссылке, т.к.  "пусто" = аллергенов нет 🤔

2023-10-09 23:45 UTC, IlerioDef commented on core/models.py
> +    name = models.CharField(max_length=255, null=False, blank=False)
Done